# Generated by Django 2.1.5 on 2019-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GENERIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GDESC', models.CharField(max_length=100)),
                ('GnCode', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(max_length=60)),
                ('MFG', models.CharField(max_length=60)),
                ('Descr', models.CharField(max_length=60)),
                ('EntryDt', models.DateTimeField()),
                ('GnCode', models.CharField(max_length=60)),
                ('PACK', models.CharField(max_length=60)),
                ('STRENGTH', models.CharField(max_length=60)),
                ('CATEGORY', models.CharField(max_length=60)),
                ('MfgCode', models.CharField(max_length=60)),
                ('HPRate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Rate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('MRP', models.DecimalField(decimal_places=10, max_digits=19)),
                ('HMARGIN', models.DecimalField(decimal_places=10, max_digits=19)),
                ('RMARGIN', models.DecimalField(decimal_places=10, max_digits=19)),
                ('TAX', models.DecimalField(decimal_places=10, max_digits=19)),
                ('MST', models.DecimalField(decimal_places=10, max_digits=19)),
                ('CST', models.DecimalField(decimal_places=10, max_digits=19)),
                ('OCT', models.DecimalField(decimal_places=10, max_digits=19)),
                ('EXICE', models.DecimalField(decimal_places=10, max_digits=19)),
                ('PIS', models.CharField(max_length=60)),
                ('PISNO', models.CharField(max_length=60)),
                ('PISDATE', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COCD', models.CharField(max_length=60)),
                ('NAME', models.CharField(max_length=60)),
                ('SHRTNM', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=60)),
            ],
        ),
    ]
