# Generated by Django 2.1.5 on 2019-01-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meddata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemMaster',
            new_name='medicine',
        ),
    ]
