# Generated by Django 2.1.5 on 2019-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meddata', '0003_auto_20190117_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='CST',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='EXICE',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='HMARGIN',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='HPRate',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MST',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='OCT',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='RMARGIN',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='TAX',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
