# Generated by Django 2.1.5 on 2019-01-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meddata', '0004_auto_20190117_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='GnCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meddata.GENERIC'),
        ),
    ]
