# Generated by Django 2.1.5 on 2019-01-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meddata', '0005_auto_20190117_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='GnCode',
            field=models.CharField(max_length=60),
        ),
    ]
