# Generated by Django 2.1.5 on 2019-01-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meddata', '0008_auto_20190118_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='CATEGORY',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='CST',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Descr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='EXICE',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='GnCode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='HMARGIN',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='HPRate',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ItemCode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MFG',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MST',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MfgCode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='OCT',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='PACK',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='PIS',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='PISNO',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='RMARGIN',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='STRENGTH',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='TAX',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
